# Generated by Django 2.1.3 on 2018-11-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='event_datetime',
        ),
    ]
